ORG 0x0								;198+396 = 594
LIST_START: WORD 0x100 				;0
LIST_POINTER: WORD 0x0				;1
OPER_POINTER: WORD 0x0				;2
LOOP_COUNTER: WORD 0x0				;3
NUMBER_LENGTH: WORD 0x4				;4
OPER_POS1: WORD 0x0					;5
OPER_POS2: WORD 0x0					;6

START: CLA
LD LIST_START
ST OPER_POINTER
SUB NUMBER_LENGTH
ST LIST_POINTER
MAIN_LOOP: 
LD NUMBER_LENGTH
ST LOOP_COUNTER
SWAM LIST_POINTER
ADD NUMBER_LENGTH
ADD NUMBER_LENGTH
SWAM LIST_POINTER
INPUT: IN 0x1D
AND #0x40
BEQ INPUT
CLA
IN 0x1C
ST -(LIST_POINTER)
LOOP LOOP_COUNTER
JUMP INPUT
SIGN_INPUT: IN 0x1D
AND #0x40
BEQ SIGN_INPUT
CLA
IN 0x1C
CMP #0xE             ;ТОЧКА
BEQ MAIN_LOOP

CMP #0xB             ;ПЛЮС
BEQ PLUS

CMP #0xA             ;МИНУС
BEQ MINUS

HLT
JUMP MAIN_LOOP


ORG 0x40
PLUS:
LD OPER_POINTER
ST OPER_POS1
ADD NUMBER_LENGTH
ST OPER_POS2
LD NUMBER_LENGTH
ST LOOP_COUNTER
CLC
LOOPP:
LD (OPER_POS1)+
ADC (OPER_POS2)
CMP #0xA
BMI CHANGE_PL				  ;>=10
ADD #0x6
CLC
CMC
CHANGE_PL: 
AND #0xF
ST (OPER_POS2)+
LOOP LOOP_COUNTER
JUMP LOOPP
LD OPER_POS2
CALL PRINT_NUMBER
LD OPER_POINTER			;0x55
ADD NUMBER_LENGTH
ST OPER_POINTER
JUMP SIGN_INPUT

MINUS: LD OPER_POINTER
ST OPER_POS1
ADD NUMBER_LENGTH
ST OPER_POS2
LD NUMBER_LENGTH
ST LOOP_COUNTER
CLC
LOOPP_MINUS:
LD (OPER_POS1)+
BCC CONT
DEC
CONT: 
SUB (OPER_POS2)
CLC
BPL CHANGE_MN				  ;<0
SUB #0x6
CLC
CMC
CHANGE_MN: 
AND #0xF
ST (OPER_POS2)+
LOOP LOOP_COUNTER
JUMP LOOPP_MINUS
LD OPER_POS2					
CALL PRINT_NUMBER
LD OPER_POINTER				;0x70
ADD NUMBER_LENGTH
ST OPER_POINTER
JUMP SIGN_INPUT


ORG 0x80
PRINT_NUMBER: 
LD NUMBER_LENGTH
ST LOOP_COUNTER

PRINT_LOOP:
LD -(OPER_POS2)
PUSH
S1: IN 0xD
AND #0x40
BEQ S1
POP
ADD #0x30
OUT 0xC
LOOP $LOOP_COUNTER
JUMP PRINT_LOOP

NEXT_VALUE: IN 0xD
AND #0x40
BEQ NEXT_VALUE
LD #0x2C
OUT 0xC


RET